#coding=utf-8
#import libs 
import sys
import Window_Main_TK_cmd
import Window_Main_TK_sty
import Fun
import os
import tkinter
from   tkinter import *
import tkinter.ttk
import tkinter.font
#Add your Varial Here: (Keep This Line of comments)
#Define UI Class
class  Window_Main_TK:
    def __init__(self,root,isTKroot = True):
        uiName = self.__class__.__name__
        Fun.Register(uiName,'UIClass',self)
        self.root = root
        Fun.Register(uiName,'root',root)
        style = Window_Main_TK_sty.SetupStyle()
        if isTKroot == True:
            root.title("Form1")
            Fun.CenterDlg(uiName,root,690,459)
            root['background'] = '#efefef'
        Form_1= tkinter.Canvas(root,width = 10,height = 4)
        Form_1.place(x = 0,y = 0,width = 690,height = 459)
        Form_1.configure(bg = "#efefef")
        Form_1.configure(highlightthickness = 0)
        Fun.Register(uiName,'Form_1',Form_1)
        #Create the elements of root 
        self.Button_3 = tkinter.Button(root,text="Load CSV",width = 10,height = 4)
        Fun.Register(uiName,'Button_3',self.Button_3,'PB_Load_CSV')
        self.Button_3.place(x = 21,y = 11,width = 100,height = 28)
        #self.Button_3.configure(command=lambda:Window_Main_TK_cmd.Button_3_onCommand(uiName,"Button_3"))
        Label_6 = tkinter.Label(root,text="Decision",width = 10,height = 4)
        Fun.Register(uiName,'Label_6',Label_6)
        Label_6.place(x = 427,y = 69,width = 100,height = 20)
        Label_6.configure(relief = "flat")
        Label_7 = tkinter.Label(root,text="Identify",width = 10,height = 4)
        Fun.Register(uiName,'Label_7',Label_7)
        Label_7.place(x = 427,y = 92,width = 100,height = 20)
        Label_7.configure(relief = "flat")
        self.ComboBox_9_Variable = Fun.AddTKVariable(uiName,'ComboBox_9')
        self.ComboBox_9 = tkinter.ttk.Combobox(root,textvariable=self.ComboBox_9_Variable, state="readonly")
        Fun.Register(uiName,'ComboBox_9',self.ComboBox_9)
        self.ComboBox_9.place(x = 533,y = 46,width = 100,height = 20)
        self.ComboBox_9.configure(state = "readonly")
        self.ComboBox_9["values"]=['aa']
        self.ComboBox_9.current(0)
        self.ComboBox_10_Variable = Fun.AddTKVariable(uiName,'ComboBox_10')
        self.ComboBox_10 = tkinter.ttk.Combobox(root,textvariable=self.ComboBox_10_Variable, state="readonly")
        Fun.Register(uiName,'ComboBox_10',self.ComboBox_10)
        self.ComboBox_10.place(x = 533,y = 69,width = 100,height = 20)
        self.ComboBox_10.configure(state = "readonly")
        self.BComboBox_11_Variable = Fun.AddTKVariable(uiName,'ComboBox_11')
        self.BComboBox_11 = tkinter.ttk.Combobox(root,textvariable=self.BComboBox_11_Variable, state="readonly")
        Fun.Register(uiName,'ComboBox_11',self.BComboBox_11)
        self.BComboBox_11.place(x = 533,y = 92,width = 100,height = 20)
        self.BComboBox_11.configure(state = "readonly")
        Label_12 = tkinter.Label(root,text="Method",width = 10,height = 4)
        Fun.Register(uiName,'Label_12',Label_12)
        Label_12.place(x = 427,y = 49,width = 100,height = 20)
        Label_12.configure(relief = "flat")
        self.SeedVar = tkinter.IntVar(value=10)
        self.Spinbox_13 = tkinter.Spinbox(root,textvariable=self.SeedVar)
        Fun.Register(uiName,'Spinbox_13',self.Spinbox_13)
        self.Spinbox_13.place(x = 569,y = 127,width = 60,height = 20)
        self.Spinbox_13.configure(from_ = "0.0")
        self.Spinbox_13.configure(to = "99.0")
        self.Spinbox_13.configure(increment = "1.0")
        Label_14 = tkinter.Label(root,text="Seed",width = 10,height = 4)
        Fun.Register(uiName,'Label_14',Label_14)
        Label_14.place(x = 437,y = 127,width = 100,height = 20)
        Label_14.configure(relief = "flat")
        Label_15 = tkinter.Label(root,text="Group",width = 10,height = 4)
        Fun.Register(uiName,'Label_15',Label_15)
        Label_15.place(x = 437,y = 152,width = 100,height = 20)
        Label_15.configure(relief = "flat")
        Label_16 = tkinter.Label(root,text="Gass Random",width = 10,height = 4)
        Fun.Register(uiName,'Label_16',Label_16)
        Label_16.place(x = 437,y = 172,width = 100,height = 20)
        Label_16.configure(relief = "flat")
        Canvas_19 = tkinter.Canvas(root)
        Fun.Register(uiName,'Canvas_19',Canvas_19)
        Canvas_19.place(x = 12,y = 46,width = 418,height = 191)
        Canvas_19.configure(bg = "#ffffff")
        self.InfoLabeleText = tkinter.StringVar()
        self.InfoLabeleText.set("This is Info")
        self.BLabel_20 = tkinter.Label(root,textvariable=self.InfoLabeleText,width = 10,height = 4)
        Fun.Register(uiName,'Label_20',self.BLabel_20)
        self.BLabel_20.place(x = 17,y = 252,width = 410,height = 20)
        self.BLabel_20.configure(relief = "ridge")

        self.BestLabeleText = tkinter.StringVar()
        self.BestLabeleText.set("This is Best")

        self.Label_21 = tkinter.Label(root,textvariable=self.BestLabeleText,width = 10,height = 4)
        Fun.Register(uiName,'Label_21',self.Label_21)
        self.Label_21.place(x = 17,y = 281,width = 410,height = 20)
        self.Label_21.configure(relief = "ridge")

        self.StatusLabeleText = tkinter.StringVar()
        self.StatusLabeleText.set("This is Status")

        self.Label_22 = tkinter.Label(root,textvariable=self.StatusLabeleText,width = 10,height = 4)
        Fun.Register(uiName,'Label_22',self.Label_22)
        self.Label_22.place(x = 17,y = 307,width = 410,height = 122)
        self.Label_22.configure(relief = "ridge")
        Label_18 = tkinter.Label(root,text="Alpha",width = 10,height = 4)
        Fun.Register(uiName,'Label_18',Label_18)
        Label_18.place(x = 437,y = 212,width = 100,height = 20)
        Label_18.configure(relief = "flat")
        Label_23 = tkinter.Label(root,text="Area Random",width = 10,height = 4)
        Fun.Register(uiName,'Label_23',Label_23)
        Label_23.place(x = 437,y = 192,width = 100,height = 20)
        Label_23.configure(relief = "flat")
        self.GropeVar = tkinter.IntVar(value=5)
        self.Spinbox_24 = tkinter.Spinbox(root,textvariable=self.GropeVar)
        Fun.Register(uiName,'Spinbox_24',self.Spinbox_24)
        self.Spinbox_24.place(x = 569,y = 152,width = 60,height = 20)
        self.Spinbox_24.configure(from_ = "0.0")
        self.Spinbox_24.configure(to = "99.0")
        self.Spinbox_24.configure(increment = "1.0")
        self.GassVar = tkinter.IntVar(value=10)
        self.Spinbox_25 = tkinter.Spinbox(root,textvariable=self.GassVar)
        Fun.Register(uiName,'Spinbox_25',self.Spinbox_25)
        self.Spinbox_25.place(x = 569,y = 172,width = 60,height = 20)
        self.Spinbox_25.configure(from_ = "0.0")
        self.Spinbox_25.configure(to = "99.0")
        self.Spinbox_25.configure(increment = "1.0")
        self.AreaVar = tkinter.IntVar(value=5)
        self.Spinbox_26 = tkinter.Spinbox(root,textvariable=self.AreaVar)
        Fun.Register(uiName,'Spinbox_26',self.Spinbox_26)
        self.Spinbox_26.place(x = 569,y = 192,width = 60,height = 20)
        self.Spinbox_26.configure(from_ = "0.0")
        self.Spinbox_26.configure(to = "99.0")
        self.Spinbox_26.configure(increment = "1.0")
        self.AlphaVar = tkinter.DoubleVar(value=10)
        self.Spinbox_27 = tkinter.Spinbox(root,textvariable=self.AlphaVar)
        Fun.Register(uiName,'Spinbox_27',self.Spinbox_27)
        self.Spinbox_27.place(x = 569,y = 212,width = 60,height = 20)
        self.Spinbox_27.configure(from_ = "0.0")
        self.Spinbox_27.configure(to = "99.0")
        self.Spinbox_27.configure(increment = "1.0")
        self.Button_32 = tkinter.Button(root,text="Load",width = 10,height = 4)
        Fun.Register(uiName,'Button_32',self.Button_32,'PB_Load')
        self.Button_32.place(x = 436,y = 336,width = 100,height = 28)
        #self.Button_32.configure(command=lambda:Window_Main_TK_cmd.Button_32_onCommand(uiName,"Button_32"))
        self.Button_33 = tkinter.Button(root,text="Save",width = 10,height = 4)
        Fun.Register(uiName,'Button_33',self.Button_33,'PB_Save')
        self.Button_33.place(x = 541,y = 336,width = 100,height = 28)
        #self.Button_33.configure(command=lambda:Window_Main_TK_cmd.Button_33_onCommand(uiName,"Button_33"))
        self.Button_34 = tkinter.Button(root,text="Run",width = 10,height = 4)
        Fun.Register(uiName,'Button_34',self.Button_34,'PB_Run')
        self.Button_34.place(x = 436,y = 368,width = 100,height = 28)
        #self.Button_34.configure(command=lambda:Window_Main_TK_cmd.Button_34_onCommand(uiName,"Button_34"))
        self.Button_39 = tkinter.Button(root,text="Fail",width = 10,height = 4)
        Fun.Register(uiName,'Button_39',self.Button_39,'PB_Optmize')
        self.Button_39.place(x = 541,y = 368,width = 100,height = 28)
        self.Button_36 = tkinter.Button(root,text="Reset",width = 10,height = 4)
        Fun.Register(uiName,'Button_36',self.Button_36,'PB_Reset')
        self.Button_36.place(x = 436,y = 401,width = 100,height = 28)
        #self.Button_36.configure(command=lambda:Window_Main_TK_cmd.Button_36_onCommand(uiName,"Button_36"))
        self.Button_37 = tkinter.Button(root,text="Stop",width = 10,height = 4)
        Fun.Register(uiName,'Button_37',self.Button_37,'PB_Stop')
        self.Button_37.place(x = 541,y = 401,width = 100,height = 28)
        #self.Button_37.configure(command=lambda:Window_Main_TK_cmd.Button_37_onCommand(uiName,"Button_37"))
        self.Button_38 = tkinter.Button(root,text="Optmize",width = 10,height = 4)
        Fun.Register(uiName,'Button_38',self.Button_38)
        self.Button_38.place(x = 541,y = 368,width = 100,height = 28)
        #self.Button_38.configure(command=lambda:Window_Main_TK_cmd.Button_38_onCommand(uiName,"Button_38"))
        Label_31 = tkinter.Label(root,text="A Div is 1.5",width = 10,height = 4)
        Fun.Register(uiName,'Label_31',Label_31)
        Label_31.place(x = 436,y = 252,width = 100,height = 20)
        Label_31.configure(relief = "flat")
        Label_30 = tkinter.Label(root,text="A Lim is 0.005",width = 10,height = 4)
        Fun.Register(uiName,'Label_30',Label_30)
        Label_30.place(x = 436,y = 232,width = 100,height = 20)
        Label_30.configure(relief = "flat")
        #Inital all element's Data 
        Fun.InitElementData(uiName)
        #Add Some Logic Code Here: (Keep This Line of comments)


#Create the root of Kinter 
if  __name__ == '__main__':
    root = tkinter.Tk()
    MyDlg = Window_Main_TK(root)
    root.mainloop()
